### ISSUE TITLE
开启JJ 调用摄像头后闪退 

### ISSUE THREAD

**Issue by iOS-Misaki** [jezzmemo/JJException#46]
**Describe the bug**
开启JJExceptionGuardKVOCrash防护 调用摄像头会闪退 
在#import "NSObject+KVOCrash.m"中cleanObservers里面会闪退
- (void)cleanObservers{
    for (KVOObjectItem* item in self.observers) {
        [self.whichObject removeObserver:item.observer forKeyPath:item.keyPath];
    }
}

打印出 item.observer 是
<AVCaptureSession: 0x28090cee0 [AVCaptureSessionPresetPhoto]>
	<AVCaptureDeviceInput: 0x280b865e0 [后置双镜头]> -> (null)
	<AVCaptureDeviceInput: 0x280b865e0 [后置双镜头]> -> <AVCapturePhotoOutput: 0x280b945e0>
	<AVCaptureDeviceInput: 0x280b865e0 [后置双镜头]> -> <AVCaptureMetadataOutput: 0x280bb6d00>

所有苹果手机型号和系统都会闪退

**Comment by jezzmemo** [comment]
用什么方式打开摄像头的？麻烦描述下，最好简单贴下代码

**Comment by iOS-Misaki** [comment]
self.imagePickerController = [UIImagePickerController new];
        self.imagePickerController.delegate = self;
        BOOL isCameraSupporet = [UIImagePickerController isSourceTypeAvailable:UIImagePickerControllerSourceTypeCamera];
        if (isCameraSupporet)
        {
            self.imagePickerController.sourceType = UIImagePickerControllerSourceTypeCamera;
            self.imagePickerController.allowsEditing = YES;
            self.imagePickerController.showsCameraControls = YES;
        }
        [self presentViewController:self.imagePickerController animated:YES completion:^{
            
        }];

打开相机后，点击拍照，self.imagePickerController消失的时候，发生闪退

**Comment by jezzmemo** [comment]
对了，你用的JJException是什么版本？

**Comment by iOS-Misaki** [comment]
0.1.2版本

**Comment by jezzmemo** [comment]
麻烦升级到0.1.9版本，我记得这个问题解决了的，
```
pod repo update
```

**Comment by iOS-Misaki** [comment]
> 麻烦升级到0.1.9版本，我记得这个问题解决过
> 
> ```
> pod repo update
> ```
pod search  JJException  只有0.1.8 版本
<img width="941" alt="2019-01-08 11 43 56" src="https://user-images.githubusercontent.com/12726780/50808697-bc518200-133a-11e9-98a7-c263607741de.png">

**Comment by jezzmemo** [comment]
```
Handle the objective-c crash exception.
   pod 'JJException', '~> 0.1.9'
   - Homepage: https://github.com/jezzmemo/JJException
   - Source:   https://github.com/jezzmemo/JJException.git
   - Versions: 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.9, 0.0.8,
   0.0.7, 0.0.6, 0.0.4, 0.0.3 [master repo]
   - Subspecs:
     - JJException/All (0.1.9)
     - JJException/ARC (0.1.9)
     - JJException/Swizzle (0.1.9)
     - JJException/Main (0.1.9)
     - JJException/MRC (0.1.9)
     - JJException/DeallocBlock (0.1.9)
```
应该还是你本地的repo有问题，我查询到0.1.9了
